spring.application.name=authsys

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=gauthamgautham

# This tells Spring to automatically create the database tables based on our Java code!
spring.jpa.hibernate.ddl-auto=update